name: 📖 Documentation improvement
- task: SpecFlowPlus@0
  inputs:
    generatorSource: 'FeatureFolder'
    projectFilePath: 'TonyProject'
description: Suggest improvements to our documentation
title: "[DOCS]: "
labels: [documentation] 
body:
- type: markdown
  attributes:
    value: Thanks for submitting this documentation improvement request!
- type: dropdown
  attributes:
    label: Type of improvement
    multiple: false
    options:
    - Add a new page or user guide
    - Fix typos
    - Improve explanations
    - Improve root-level Markdown files
- type: textarea
  attributes:
    label: Description
    description: What should we improve about the documentation?
  validations:
    required: true
- type: textarea
  attributes:
    label: Documentation links 
    description: If applicable, please provide direct links to the pages.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: Please share anything that will give us more context about this request.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Commitments
    options:
      - label: I agree to follow Boa Constrictor's [Code of Conduct](https://q2ebanking.github.io/boa-constrictor/contributing/code-of-conduct/).
        required: true
      - label: I want to work on this issue myself. (This is voluntary, not required.)
        required: false